version: "3"
services:
  api:
    build: .
    expose:
      - "8000"
    ports:
      - "8000:8000"
    env_file:
        ./.env
    environment:
      VIRTUAL_HOST: ${VIRTUAL_HOST}
      VIRTUAL_PORT: ${VIRTUAL_PORT}
      LETSENCRYPT_HOST: ${LETSENCRYPT_HOST}
    networks:
      - proxynet

networks:
  proxynet:
    external:
      name: ${PROXY_NETWORK}
